# SAM.gov Daily Digest Procedure
#
# Generates a daily digest of SAM.gov opportunities with per-opportunity
# LLM analysis, PDF generation, and email delivery.
#
# Triggers:
# - Cron: Weekdays at 8 AM
# - Manual: Via API or UI

name: SAM.gov Daily Digest
slug: sam_daily_digest
description: >
  Generate a daily digest of federal contracting opportunities from SAM.gov.
  Queries notices from the past 24 hours, generates detailed per-opportunity
  analysis, creates a PDF report, and emails it to configured recipients.

version: "1.0.0"
is_system: true
tags:
  - sam
  - digest
  - daily
  - automation
  - email

parameters:
  - name: recipients
    type: str
    description: Email addresses to send the digest to (comma-separated if multiple)
    required: false
    default: "dlarrimore@amivero.com"
    example: "dlarrimore@amivero.com, other@example.com"

  - name: posted_within_days
    type: int
    description: Only include notices posted within N days
    required: false
    default: 1

  - name: max_notices
    type: int
    description: Maximum notices to include in digest
    required: false
    default: 50

  - name: company_name
    type: str
    description: Company name for the analysis context
    required: false
    default: "Amivero, LLC"

  - name: company_context
    type: str
    description: Company context for relevance analysis
    required: false
    default: >
      8(a), Woman-Owned Small Business (WOSB). Primary customer: General Services Administration, Department of Transportation, U.S. Department
      of Homeland Security (DHS) including CBP, USCIS, ICE. Strategic growth
      targets: TSA, CISA, FEMA. We also are strategically targeting Department of State. Core capabilities: AI & Advanced Analytics,
      Fraud Detection, SecDevOps & Cloud Engineering, Software Development,
      RPA & Intelligent Automation, Program Management, Business Intelligence.

triggers:
  - type: cron
    cron_expression: "0 8 * * 1-5"  # 8 AM Monday-Friday

steps:
  # Step 1: Query recent notices
  - name: query_notices
    function: search_notices
    description: Query SAM.gov notices from the past 24 hours
    params:
      posted_within_days: "{{ params.posted_within_days }}"
      include_solicitation: true
      limit: "{{ params.max_notices }}"
    on_error: fail

  # Step 2: Analyze each opportunity individually
  - name: analyze_opportunities
    function: llm_generate
    description: Generate detailed analysis for each opportunity
    foreach: "{{ steps.query_notices }}"
    params:
      system_prompt: "You are an internal business development and acquisition analyst for {{ params.company_name }}.\n\nABOUT THE COMPANY:\n{{ params.company_context }}\n\nPRIMARY GOAL:\nProvide a concise, executive-ready assessment of whether this SAM.gov notice represents a real, actionable opportunity.\n\nGENERAL GUIDANCE:\n- Most Special Notices, Award Notices, and Sole Source Justifications are NOT actionable.\n- Be decisive and concise.\n- Avoid FAR explanations unless they materially affect actionability.\n\nREQUIRED OUTPUT FORMAT:\n\n### Opportunity Overview\n**Disposition**: ACTIONABLE | MONITOR | IGNORE\n**Title**: <Exact title from input>\n**Agency / Component**: <Agency, Subcomponent>\n**Notice Type**: <SAM notice type>\n**SAM.gov Link**: <Include the exact Link URL provided in the input>\n\n### Key Dates\n- List any: Response deadline, RFP release date, Industry Day date\n\n### Acquisition Summary\n- 2-4 concise bullets describing what the government is buying\n\n### Contract Details\n- Contract type, estimated value, period of performance (if available)\n\n### Relevance to {{ params.company_name }}\n- Connect to company strategy and capabilities, or state 'Not relevant'\n\n### Recommended Action\n- One clear sentence"
      prompt: "Analyze this opportunity:\n\nTitle: {{ item.title }}\nNotice ID: {{ item.fields.sam_notice_id }}\nNotice Type: {{ item.display_type }} ({{ item.fields.notice_type }})\nPosted: {{ item.fields.posted_date }}\nResponse Deadline: {{ item.fields.response_deadline or 'Not specified' }}\nAgency: {{ item.fields.agency_name or 'Unknown' }}\nBureau: {{ item.fields.bureau_name or 'Unknown' }}\nNAICS: {{ item.fields.naics_code or 'Not specified' }}\nSet-Aside: {{ item.fields.set_aside_code or 'None' }}\nLink: {{ item.metadata.ui_link }}\n\nDescription:\n{{ item.metadata.description or 'No description available' }}"
      max_tokens: 1000
      temperature: 0.3
    on_error: continue

  # Step 3: Generate executive summary
  - name: executive_summary
    function: llm_generate
    description: Generate executive summary of all opportunities
    condition: "steps.analyze_opportunities"
    params:
      system_prompt: "You are a senior Business Development executive at {{ params.company_name }}. Create an executive-ready daily SAM.gov intelligence summary."
      prompt: "Create an executive summary for the daily SAM.gov digest dated {{ now().strftime('%B %d, %Y') }}.\n\nTotal notices analyzed: {{ steps.analyze_opportunities | length }}\n\nIndividual Analyses:\n{% for analysis in steps.analyze_opportunities %}{% if analysis.success %}\n---\n{{ analysis.result }}\n{% endif %}{% endfor %}\n\nREQUIRED STRUCTURE:\n\n## Executive Summary\n\n### Action Required\n- List opportunities marked ACTIONABLE with title, agency, and deadline\n\n### Monitor List\n- List opportunities marked MONITOR with brief reason\n\n### Key Takeaways\n- 3-5 bullets on DHS activity trends, notable opportunities, strategic implications for {{ params.company_name }}"
      max_tokens: 1500
      temperature: 0.3
    on_error: continue

  # Step 4: Build full report markdown
  - name: build_report
    function: llm_generate
    description: Compile full markdown report
    params:
      system_prompt: "You are a report formatter. Combine the provided content into a well-structured markdown document. Do not add or remove content, just format it cleanly."
      prompt: "Create a formatted markdown report:\n\n# SAM.gov Daily Intelligence Brief\n\n**Date**: {{ now().strftime('%B %d, %Y') }}\n**Prepared for**: {{ params.company_name }}\n**Source**: SAM.gov (past {{ params.posted_within_days }} day{% if params.posted_within_days > 1 %}s{% endif %})\n**Notices Analyzed**: {{ steps.query_notices | length if steps.query_notices else 0 }}\n\n---\n\n{{ steps.executive_summary if steps.executive_summary else '## Executive Summary\\n\\nNo executive summary available.' }}\n\n---\n\n## Detailed Opportunity Assessments\n\n{% if steps.analyze_opportunities %}{% for analysis in steps.analyze_opportunities %}{% if analysis.success %}\n### {{ loop.index }}. Analysis\n\n{{ analysis.result }}\n\n---\n\n{% endif %}{% endfor %}{% else %}\nNo opportunities to analyze.\n{% endif %}\n\n---\n\n*Generated by Curatore SAM.gov Integration*"
      max_tokens: 4000
    on_error: fail

  # Step 5: Generate PDF
  - name: generate_pdf
    function: generate_document
    description: Convert report to PDF
    params:
      format: pdf
      content: "{{ steps.build_report }}"
      title: "SAM.gov Daily Brief - {{ now().strftime('%Y-%m-%d') }}"
      filename: "sam_daily_brief_{{ now().strftime('%Y%m%d') }}.pdf"
    on_error: fail

  # Step 6: Save markdown to storage
  - name: save_markdown
    function: create_artifact
    description: Save markdown report to storage
    params:
      content: "{{ steps.build_report }}"
      filename: "sam_daily_digest_{{ now().strftime('%Y%m%d') }}.md"
      content_type: text/markdown
      folder: digests/sam/daily
    on_error: continue

  # Step 7: Build email body with summary
  - name: build_email_body
    function: llm_generate
    description: Create concise email body
    params:
      system_prompt: "You are writing a brief email body. Be concise and professional. Use plain text, no markdown. Read the analysis results carefully to identify ACTIONABLE and MONITOR items."
      prompt: "Write a brief email body for the SAM.gov daily digest dated {{ now().strftime('%B %d, %Y') }}.\n\nTotal notices analyzed: {{ steps.query_notices | length if steps.query_notices else 0 }}\n\nINDIVIDUAL OPPORTUNITY ANALYSES (review these to identify ACTIONABLE and MONITOR items):\n{% for analysis in steps.analyze_opportunities %}{% if analysis.success %}\n---\nItem {{ loop.index }}:\n{{ analysis.result }}\n{% endif %}{% endfor %}\n\nINSTRUCTIONS:\n1. Open with a one-line greeting\n2. State the number of opportunities reviewed\n3. List any ACTIONABLE items by title and deadline (if any were marked ACTIONABLE above)\n4. List any MONITOR items briefly (if any were marked MONITOR above)\n5. If there are ACTIONABLE or MONITOR items, emphasize them\n6. Mention the PDF attachment has full details with links\n7. Close professionally\n\nIMPORTANT: Carefully read each analysis above. If ANY item has 'Disposition: ACTIONABLE' or 'Disposition: MONITOR', you MUST mention it in the email. Do not say 'no actionable items' if there are items marked ACTIONABLE or MONITOR.\n\nKeep it under 250 words."
      max_tokens: 500
    on_error: continue

  # Step 8: Send email with PDF attachment
  - name: send_email
    function: send_email
    description: Email the digest to recipients
    params:
      to: "{{ params.recipients }}"
      subject: "SAM.gov Daily Brief - {{ now().strftime('%B %d, %Y') }} ({{ steps.query_notices | length if steps.query_notices else 0 }} opportunities)"
      body: "{{ steps.build_email_body if steps.build_email_body else 'Please see the attached PDF for today''s SAM.gov daily digest.' }}"
      html: false
      attachments:
        - filename: "{{ steps.generate_pdf.filename }}"
          content: "{{ steps.generate_pdf.document_base64 }}"
          content_type: "application/pdf"
    on_error: fail

outputs:
  - type: result
    config:
      include_steps:
        - query_notices
        - analyze_opportunities
        - executive_summary
        - generate_pdf
        - send_email

on_error: continue
