# SAM.gov Weekly Digest Procedure
#
# Generates a weekly digest of SAM.gov opportunities based on configured
# search criteria. Searches notices and includes parent solicitation context
# when available.
#
# Triggers:
# - Cron: Sunday at 6 PM
# - Event: After a SAM pull completes (sam_pull.completed)

name: SAM.gov Weekly Digest
slug: sam_weekly_digest
description: >
  Generate a weekly digest of federal contracting opportunities from SAM.gov.
  Queries notices from the past 7 days, includes linked solicitation context,
  generates AI summaries, and creates a formatted report.

version: "1.1.0"
is_system: true
tags:
  - sam
  - digest
  - weekly
  - automation

parameters:
  - name: naics_codes
    type: list
    description: NAICS codes to filter opportunities
    required: false
    default: []

  - name: set_asides
    type: list
    description: Set-aside types to filter (e.g., SBA, 8(a))
    required: false
    default: []

  - name: posted_within_days
    type: int
    description: Only include notices posted within N days
    required: false
    default: 7

  - name: include_summaries
    type: bool
    description: Generate AI summaries for opportunities
    required: false
    default: true

  - name: max_notices
    type: int
    description: Maximum notices to include in digest
    required: false
    default: 50

triggers:
  - type: cron
    cron_expression: "0 18 * * 0"  # 6 PM Sunday

  - type: event
    event_name: sam_pull.completed
    event_filter:
      status: completed

steps:
  - name: query_notices
    function: search_notices
    description: Query recent SAM.gov notices with solicitation context
    params:
      posted_within_days: "{{ params.posted_within_days }}"
      include_solicitation: true
      limit: "{{ params.max_notices }}"
    on_error: fail

  - name: summarize_notices
    function: llm_summarize
    description: Generate a summary of all notices
    condition: "steps.query_notices and len(steps.query_notices) > 0"
    params:
      text: >
        {% for notice in steps.query_notices %}
        ## {{ notice.title }}
        - Notice ID: {{ notice.fields.sam_notice_id }}
        - Type: {{ notice.display_type }} ({{ notice.fields.notice_type }})
        - Posted: {{ notice.fields.posted_date }}
        - Deadline: {{ notice.fields.response_deadline or 'N/A' }}
        - Agency: {{ notice.fields.agency_name or 'N/A' }}
        - NAICS: {{ notice.fields.naics_code or 'N/A' }}
        - Set-Aside: {{ notice.fields.set_aside_code or 'None' }}
        - Description: {{ notice.metadata.description_preview or 'N/A' }}
        {% if notice.metadata.changes_summary %}
        - Changes: {{ notice.metadata.changes_summary }}
        {% endif %}
        {% if notice.fields.solicitation %}

        ### Parent Solicitation: {{ notice.fields.solicitation.solicitation_number }}
        - Title: {{ notice.fields.solicitation.title }}
        - Status: {{ notice.fields.solicitation.status }}
        - Total Notices: {{ notice.fields.solicitation.notice_count }}
        - Description: {{ notice.fields.solicitation.description_preview or 'N/A' }}
        {% endif %}

        {% endfor %}
      style: bullets
      focus: key requirements, deadlines, and notable changes from previous versions
      max_length: 1500
    on_error: continue

  - name: generate_digest
    function: llm_generate
    description: Generate the formatted weekly digest
    params:
      system_prompt: >
        You are a federal contracting analyst creating a weekly digest for
        a business development team. Be concise and highlight the most
        actionable opportunities. For notices linked to solicitations,
        provide context about the overall opportunity.
      prompt: >
        Create a weekly digest email for the week ending {{ now().strftime('%B %d, %Y') }}.

        Total notices found: {{ steps.query_notices | length if steps.query_notices else 0 }}

        {% if steps.summarize_notices %}
        Summary: {{ steps.summarize_notices }}
        {% endif %}

        {% if steps.query_notices %}
        Recent Notices:
        {% for notice in steps.query_notices[:15] %}
        - {{ notice.title }}
          Type: {{ notice.display_type }}
          Posted: {{ notice.fields.posted_date }}
          Deadline: {{ notice.fields.response_deadline or 'N/A' }}
          Agency: {{ notice.fields.agency_name or 'Unknown' }}
          {% if notice.fields.solicitation %}
          Solicitation: {{ notice.fields.solicitation.solicitation_number }}
          {% endif %}
          Link: {{ notice.metadata.ui_link }}
        {% endfor %}
        {% else %}
        No new notices matching your criteria this week.
        {% endif %}

        Format as a professional email digest with sections for:
        1. Executive Summary (2-3 sentences highlighting key opportunities)
        2. New Solicitations (notices that are original postings)
        3. Amendments & Updates (notices updating existing solicitations)
        4. Special Notices (standalone informational notices)
        5. Upcoming Deadlines (sorted by response deadline)
        6. Next Steps

      max_tokens: 2500
    on_error: fail

  - name: save_digest
    function: create_artifact
    description: Save digest to object storage
    params:
      content: "{{ steps.generate_digest }}"
      filename: "sam_weekly_digest_{{ now().strftime('%Y%m%d') }}.md"
      content_type: text/markdown
      folder: digests/sam
    on_error: continue

outputs:
  - type: result
    config:
      include_steps:
        - query_notices
        - generate_digest
        - save_digest

on_error: fail
