[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "curatore-api"
version = "0.1.0"
description = "Curatore FastAPI backend"
requires-python = ">=3.11"